//===- CoralNPUEmitAssembly.cpp - Assembly emission -----------------------===//

#include "circt/Dialect/CoralNPU/CoralNPUPasses.h"
#include "circt/Dialect/CoralNPU/CoralNPUOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"
#include "llvm/Support/raw_ostream.h"

using namespace circt;
using namespace circt::coralnpu;

namespace circt {
namespace coralnpu {
#define GEN_PASS_DEF_CORALNPUEMITASSEMBLY
#include "circt/Dialect/CoralNPU/Passes.h.inc"
} // namespace coralnpu
} // namespace circt

namespace {

static void emitInstruction(mlir::Operation *op, llvm::raw_ostream &os) {
  os << "  ";
  if (auto addOp = mlir::dyn_cast<ScalarAddOp>(op))
    os << "add";
  else if (auto subOp = mlir::dyn_cast<ScalarSubOp>(op))
    os << "sub";
  else if (auto mulOp = mlir::dyn_cast<ScalarMulOp>(op))
    os << "mul";
  else if (auto liOp = mlir::dyn_cast<ScalarLiOp>(op))
    os << "li    x?, " << liOp.getValue();
  else if (auto vaddOp = mlir::dyn_cast<VAddOp>(op)) {
    os << "vadd.vv";
    if (vaddOp.getStripmine() > 1)
      os << "  # stripmine=" << vaddOp.getStripmine();
  } else if (auto vdotOp = mlir::dyn_cast<VDotOp>(op)) {
    os << "vdot.vv";
    if (vdotOp.getStripmine() > 1)
      os << "  # stripmine=" << vdotOp.getStripmine();
  } else if (mlir::isa<VLE8Op>(op))
    os << "vle8.v";
  else if (mlir::isa<VSE8Op>(op))
    os << "vse8.v";
  else if (mlir::isa<OuterProductOp>(op))
    os << "outer_product";
  else if (mlir::isa<BranchOp>(op))
    os << "j       .L?";
  else if (mlir::isa<ReturnOp>(op))
    os << "ret";
  else
    os << "# unknown: " << op->getName().getStringRef();
  os << "\n";
}

struct CoralNPUEmitAssemblyPass
    : public impl::CoralNPUEmitAssemblyBase<CoralNPUEmitAssemblyPass> {
  void runOnOperation() override {
    llvm::outs() << "# Coral NPU Assembly (generated by CIRCT)\n\n";
    getOperation()->walk([&](mlir::Operation *op) {
      if (op->getDialect()->getNamespace() == "coralnpu")
        emitInstruction(op, llvm::outs());
    });
    llvm::outs() << "\n# End of assembly\n";
  }
};

} // namespace

namespace circt {
namespace coralnpu {
std::unique_ptr<mlir::Pass> createCoralNPUEmitAssemblyPass() {
  return std::make_unique<CoralNPUEmitAssemblyPass>();
}
} // namespace coralnpu
} // namespace circt
